### ISSUE TITLE
Fixes for Integration with Cocoapods

### ISSUE THREAD

**Issue by mr250724** [salemove/ios-sdk-widgets#191]
For better integration with cocoa pods, please remove the 'Window' directory. The file GliaWindow.swift is being pulled in and won't allow the project to build. However, the sample project does build because this file is not included in the project.
Also, please add this line to GliaWidgets.podspec:
`s.resources = ['GliaWidgets/Resources/*.xcassets', 'GliaWidgets/Resources/**/*']`
This will allow the image and strings resources to be imported. 
Thanks!

**Comment by dukhovnyi** [comment]
Hi @mr250724, thank you for creating the issue. 
We've prepared the fix for it and will update our podspec to unblock you using the 0.5.8 version.

Looks like you have used podspec file from the repository that is totally okay, but I'd like to inform you that you also could use our podspec repository and integrate GliaWidgets this way

```ruby
source 'https://github.com/salemove/glia-ios-podspecs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '12.0'

target 'Widgets-Cocoapods' do
  use_frameworks!

  pod 'GliaWidgets'

end
```

**Comment by dukhovnyi** [comment]
@mr250724 We have updated the podspec and repository source code, so now it should work well. 
Please clean the Pods folder and reinstall pods with `--repo-update` flag. And let us know if it works well for you.

```bash
rm -rf Pods
pod install --repo-update
```

**Comment by mr250724** [comment]
It is working, thank you.
